name: deploy skript backend
on:
  push:
    branches:
      - dev
    paths:
      - backend/**
   
  
    
jobs:
  
  deploy-api:
    runs-on: ubuntu-latest
    steps:
    - name: deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd engineerprofile360.web/
          git pull origin dev
          docker-compose up -d --build api

